export const INCREMENT_BREAK            = 'INCREMENT_BREAK'
export const DECREMENT_BREAK            = 'DECREASE_BREAK'
export const INCREMENT_SESSION          = 'INCREMENT_SESSION'
export const DECREMENT_SESSION          = 'DECREMENT_SESSION'
export const DECREASE_TIMER             = 'DECREASE_TIMER'
export const SET_TIME_LEFT_IN_SECOND    = 'SET_TIME_LEFT_IN_SECOND'
export const SET_BREAK_LENGTH   = 'SET_BREAK_LENGTH'