export const INCREMENT_BREAK    = 'INCREMENT_BREAK'
export const DECREMENT_BREAK    = 'DECREASE_BREAK'
export const INCREMENT_SESSION  = 'INCREMENT_SESSION'
export const DECREMENT_SESSION  = 'DECREMENT_SESSION'